
base:
    board_l: 10
    board_w: 20
    n_agents: 3
    n_actions: 4
    d_model: 32
    activation: 'relu'
    kernel_size: 3
    gamma: 0.99
    lmda: 0.85
    epsilon: 0.2
    v_weight: 1.0
    e_weight: 0.01
    buffer_size: 200
    lr: 0.001
    episodes: 2000
    train_freq: 1
    train_steps: 3
    test_freq: 20
    test_episodes: 20
    verbose: 5
    max_to_keep: 4
    record_model: 500